/** Убранный учёт рабочего времени и предоплата/постоплата. */
import { chromium } from 'playwright'
import { resolve } from 'node:path'
import { addTariff } from './lib-tariff.mjs'
const FILE = 'file://' + resolve('Аква пати — CRM (пустая касса).html')
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
const errs = []
p.on('pageerror', (e) => errs.push(e.message))
p.on('dialog', (d) => d.accept())
const ok = (n, c, x = '') => console.log(`  ${c ? 'ok  ' : 'ПЛОХО'} ${n}${x ? '  — ' + x : ''}`)
const F = (l) => p.locator('.modal-main .field-col', { hasText: l }).first()
const flat = async (s) => (await p.locator(s).innerText()).replace(/\s+/g, ' ').trim()

await p.goto(FILE, { waitUntil: 'load' })
await p.waitForTimeout(700)
for (const d of '4444') await p.getByRole('button', { name: d, exact: true }).click()
await p.waitForTimeout(700)

/* учёт рабочего времени убран */
const admins = await F('Администратор').locator('select option').allTextContents()
ok('Пометок «не в смене» и «приглашён» нет', !admins.some((t) => /не в смене|приглашён/.test(t)), admins.filter(Boolean).join(' | '))
ok('Неактивированных в списке нет', !admins.some((t) => t.includes('Романова')), admins.filter(Boolean).join(' | '))
await F('Администратор').locator('select').selectOption('Смирнова Е. В.')
await p.waitForTimeout(300)
ok('Галочки «беру ответственность» нет', (await p.locator('.modal-main [role=checkbox]').count()) === 0)
ok('Смену можно открыть сразу', !(await p.locator('.modal-foot').getByRole('button', { name: 'Открыть смену' }).isDisabled()))
await p.locator('.modal-foot').getByRole('button', { name: 'Открыть смену' }).click()
await p.waitForTimeout(900)

await p.goto(FILE + '#/settings')
await p.waitForTimeout(700)
const users = await flat('.tbl tbody')
ok('В сотрудниках нет «В смене» / «Не в смене»', !/В смене|Не в смене/.test(users), users.slice(0, 120))
ok('Статусы: Работает / Приглашён', users.includes('Работает') && users.includes('Приглашён'))

/* предоплата: штучный товар */
await addTariff(p, FILE, { name: 'Час игры', min: 60, price: 1000, extra: 20 })
await p.goto(FILE + '#/orders/new')
await p.waitForTimeout(700)
const postpay = p.locator('.modal-main [role=checkbox]').last()
ok('Галочка «Постоплата» есть и снята', (await postpay.getAttribute('aria-checked')) === 'false')
await p.locator('.modal-main .subtabs').getByText('Товары').click()
await p.waitForTimeout(300)
await p.locator('.cat-row', { hasText: 'Шапочка для плавания' }).getByRole('button', { name: 'Увеличить' }).click()
await p.waitForTimeout(300)
const btn = p.locator('.modal-foot').getByRole('button', { name: /Принять оплату|Создать заказ/ })
ok('Штучный без постоплаты → «Принять оплату»', (await btn.textContent()) === 'Принять оплату', await btn.textContent())
await btn.click()
await p.waitForTimeout(800)
await p.locator('.modal-foot').getByRole('button', { name: 'Принять оплату' }).click()
await p.waitForTimeout(900)
const row1 = await flat('.tbl tbody tr:first-child')
ok('Штучный заказ закрыт сразу', row1.includes('Закрыт'), row1)

/* предоплата: тариф — оплата сразу, заказ открыт */
await p.goto(FILE + '#/orders/new')
await p.waitForTimeout(700)
await p.locator('.cat-row', { hasText: 'Час игры' }).getByRole('button', { name: 'Увеличить' }).click()
await p.waitForTimeout(300)
ok('Тариф без постоплаты → тоже «Принять оплату»', (await p.locator('.modal-foot').getByRole('button', { name: 'Принять оплату' }).count()) === 1)
await p.locator('.modal-foot').getByRole('button', { name: 'Принять оплату' }).click()
await p.waitForTimeout(800)
await p.locator('.modal-foot').getByRole('button', { name: 'Принять оплату' }).click()
await p.waitForTimeout(900)
const row2 = await flat('.tbl tbody tr:first-child')
ok('Предоплаченный тариф остаётся открытым', row2.includes('Открыт'), row2)
await p.locator('.tbl tbody tr').first().click()
await p.waitForTimeout(700)
const card = await flat('.modal-aside')
ok('Оплачен полностью, остатка нет', /Остаток 0/.test(card), card.slice(0, 130))
ok('Закрыть заказ можно', !(await p.locator('.modal-foot').getByRole('button', { name: 'Закрыть заказ' }).isDisabled()))
await p.locator('.modal-head .icon-btn').click()
await p.waitForTimeout(500)

/* постоплата */
await p.goto(FILE + '#/orders/new')
await p.waitForTimeout(700)
await p.locator('.cat-row', { hasText: 'Час игры' }).getByRole('button', { name: 'Увеличить' }).click()
await p.locator('.modal-main [role=checkbox]').last().click()
await p.waitForTimeout(300)
const btn2 = p.locator('.modal-foot').getByRole('button', { name: /Принять оплату|Создать заказ/ })
ok('С постоплатой кнопка «Создать заказ»', (await btn2.textContent()) === 'Создать заказ', await btn2.textContent())
ok('Подсказка про постоплату', (await flat('.modal-hint')).includes('Постоплата'), await flat('.modal-hint'))
await btn2.click()
await p.waitForTimeout(900)
const row3 = await flat('.tbl tbody tr:first-child')
ok('Постоплатный заказ открыт и не оплачен', row3.includes('Открыт') && row3.includes('Не выбрано'), row3)
await p.locator('.tbl tbody tr').first().click()
await p.waitForTimeout(700)
const card3 = await flat('.modal-aside')
ok('Висит остаток к оплате', /Остаток 1 000/.test(card3), card3.slice(0, 130))
ok('Закрыть заказ нельзя до оплаты', await p.locator('.modal-foot').getByRole('button', { name: 'Закрыть заказ' }).isDisabled())
await p.locator('.modal-foot').getByRole('button', { name: 'Принять оплату' }).click()
await p.waitForTimeout(800)
await p.locator('.modal-foot').getByRole('button', { name: 'Принять оплату' }).click()
await p.waitForTimeout(900)
const row4 = await flat('.tbl tbody tr:first-child')
ok('После оплаты постоплатный заказ закрыт', row4.includes('Закрыт'), row4)

await b.close()
console.log(errs.length ? '\nОШИБКИ: ' + errs.join(' | ') : '\nОшибок нет.')
